# Generated by Django 4.1.13 on 2024-08-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Melody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('order_num', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=200)),
                ('melody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.melody')),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.TextField()),
                ('order_num', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=200)),
                ('melody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.melody')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='images')),
                ('order_num', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('comment', models.CharField(max_length=200)),
                ('melody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.melody')),
            ],
        ),
    ]
