# Generated by Django 4.1.13 on 2024-08-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tab',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='tab',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tab',
            name='order_num',
        ),
        migrations.RemoveField(
            model_name='url',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='url',
            name='date',
        ),
        migrations.RemoveField(
            model_name='url',
            name='order_num',
        ),
    ]
