# Generated by Django 4.1.13 on 2024-08-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comment',
        ),
        migrations.AddField(
            model_name='image',
            name='image_comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='order_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='melody',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='melody',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='melody',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tab',
            name='tab',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
